In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("renewable-share-energy.csv")

In [5]:
df.head(10)

   Entity      Code  Year  Renewables
0  Africa  OWID_AFR  1965    5.419266
1  Africa  OWID_AFR  1966    5.772398
2  Africa  OWID_AFR  1967    5.963763
3  Africa  OWID_AFR  1968    6.605470
4  Africa  OWID_AFR  1969    7.505726
5  Africa  OWID_AFR  1970    8.649540
6  Africa  OWID_AFR  1971    7.689221
7  Africa  OWID_AFR  1972    8.276323
8  Africa  OWID_AFR  1973    8.068716
9  Africa  OWID_AFR  1974    8.736290

In [6]:
df.describe()

              Year   Renewables
count  6379.000000  6379.000000
mean   1995.358207    11.118055
std      17.145077    13.269040
min    1965.000000     0.000000
25%    1981.000000     2.126912
50%    1996.000000     6.550673
75%    2010.000000    15.007385
max    2024.000000    86.126360

In [8]:
df.columns

Index(['Entity', 'Code', 'Year', 'Renewables'], dtype='object')

In [9]:
print(df.iloc[-1])

Entity            World
Code           OWID_WRL
Year               2024
Renewables    14.822139
Name: 6378, dtype: object

In [13]:
#which 10 countries has the highest renewable energy share in the latest year?

df_2024 = df[df["Year"] == 2024]
top_countries = df_2024.sort_values(
    by="Renewables",
    ascending=False
)
print(top_countries[["Entity", "Renewables"]].head(10))

                        Entity  Renewables
2248                   Iceland   80.498090
3723                    Norway   71.811970
5458                    Sweden   51.317930
733                     Brazil   49.615980
4303  Other South America (EI)   44.722060
479                    Austria   43.347355
3448               New Zealand   42.554394
1368                   Denmark   41.722164
5518               Switzerland   39.867900
4663                  Portugal   39.740760